version: 2.1
parameters:
  url:
    type: string
    default: "latest"

jobs:
  extract-csv:
    docker:
      - image: geographica/gdal2:2.4.0
    steps:
      - checkout
      - run:
          name: create work directory
          command: |
            mkdir -p /tmp/workspace/target
      - run:
          name: install base software
          command: |
            apt-get update && apt-get install -y vim dbview unzip wget less
      - run:
          name: get remote file
          command: wget <<pipeline.parameters.url>> -O /tmp/workspace/data.zip
      - run:
          name: transform fileGDB to csv
          command: |
            $PWD/scripts/geodb2csv.sh data  BedrijventerreinPerceel
      - run:
          name: List the files which have been created
          command: ls -al /tmp/workspace/*
      - run:
          name: Test correct number of files
          command: test `ls | wc -l` -eq 20
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/
  transform2RDF:
    docker:
      - image: bertvannuffelen/any2jsonld:bedrijventerrein.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: convert all csv files
          command: |
            cp $PWD/scripts/Makefile /tmp/workspace
            pushd /tmp/workspace
            make rdf
      - run:
          name: List the files which have been created
          command: ls -al /tmp/workspace/*
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/
  upload:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: bash scripts/azure.sh ${SAS_TOKEN}
workflows:
  version: 2
  generate_documentation:
    jobs:
      - extract-csv
      - transform2RDF:
          requires:
            - extract-csv
      - hold:
          type: approval # presents manual approval button in the UI
          requires:
            - transform2RDF
      - upload:
          requires:
            - hold
