#!/bin/bash

SAS_TOKEN=$1

curl -X PUT -T Aanbieder.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/Aanbieder.nt?$SAS_TOKEN"
curl -X PUT -T Aanbieder.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/Aanbieder.ttl?$SAS_TOKEN"
curl -X PUT -T Bedrijventerrein.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/Bedrijventerrein.nt?$SAS_TOKEN"
curl -X PUT -T Bedrijventerrein.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/Bedrijventerrein.ttl?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel0.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel0.nt?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel0.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel0.ttl?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel1.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel1.nt?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel1.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel1.ttl?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel2.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel2.nt?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel2.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel2.ttl?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel3.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel3.nt?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel3.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel3.ttl?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel4.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel4.nt?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel4.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel4.ttl?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel5.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel5.nt?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel5.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel5.ttl?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel6.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel6.nt?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel6.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel6.ttl?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel7.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel7.nt?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel7.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel7.ttl?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel8.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel8.nt?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel8.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel8.ttl?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel9.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel9.nt?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinPerceel9.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinPerceel9.ttl?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinperceelBeperking.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinperceelBeperking.nt?$SAS_TOKEN"
curl -X PUT -T BedrijventerreinperceelBeperking.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BedrijventerreinperceelBeperking.ttl?$SAS_TOKEN"
curl -X PUT -T BeheerdeBedrijvenzone.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BeheerdeBedrijvenzone.nt?$SAS_TOKEN"
curl -X PUT -T BeheerdeBedrijvenzone.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/BeheerdeBedrijvenzone.ttl?$SAS_TOKEN"
curl -X PUT -T GeregistreerdeOrganisatie.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/GeregistreerdeOrganisatie.nt?$SAS_TOKEN"
curl -X PUT -T GeregistreerdeOrganisatie.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/GeregistreerdeOrganisatie.ttl?$SAS_TOKEN"
curl -X PUT -T OntwikkelbareBedrijvenzone.nt -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/OntwikkelbareBedrijvenzone.nt?$SAS_TOKEN"
curl -X PUT -T OntwikkelbareBedrijvenzone.ttl -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://bedrijventerreinstorevl.blob.core.windows.net/bedrijventerreinen-data/OntwikkelbareBedrijvenzone.ttl?$SAS_TOKEN"
